#create database
-- MySQL Script generated by MySQL Workbench
-- dim. 08 oct. 2017 00:07:41 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hackathon76api
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hackathon76api
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hackathon76api` DEFAULT CHARACTER SET utf8 ;
USE `hackathon76api` ;

-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User` ;

CREATE TABLE IF NOT EXISTS `User` (
  `idUser` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(155) NOT NULL,
  `token` VARCHAR(155) NULL,
  `password` VARCHAR(155) NOT NULL,
  `name` VARCHAR(155) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Zone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Zone` ;

CREATE TABLE IF NOT EXISTS `Zone` (
  `idZone` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(85) NULL,
  `description` VARCHAR(255) NOT NULL,
  `idZoneParent` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idZone`),
  INDEX `fk_Zone_Zone1_idx` (`idZoneParent` ASC),
  CONSTRAINT `fk_Zone_Zone1`
    FOREIGN KEY (`idZoneParent`)
    REFERENCES `Zone` (`idZone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Category` ;

CREATE TABLE IF NOT EXISTS `Category` (
  `idCategory` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(155) NULL,
  `idParentCategory` INT UNSIGNED NULL,
  `type` TINYINT(1) UNSIGNED NOT NULL,
  PRIMARY KEY (`idCategory`),
  INDEX `fk_Category_Category1_idx` (`idParentCategory` ASC),
  CONSTRAINT `fk_Category_Category1`
    FOREIGN KEY (`idParentCategory`)
    REFERENCES `Category` (`idCategory`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Complaint`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Complaint` ;

CREATE TABLE IF NOT EXISTS `Complaint` (
  `idComplaint` INT UNSIGNED NOT NULL,
  `description` TEXT NULL,
  `idUser` INT UNSIGNED NOT NULL,
  `idZone` INT UNSIGNED NOT NULL,
  `idCategory` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idComplaint`),
  INDEX `fk_Complaint_User_idx` (`idUser` ASC),
  INDEX `fk_Complaint_Zone1_idx` (`idZone` ASC),
  INDEX `fk_Complaint_Category1_idx` (`idCategory` ASC),
  CONSTRAINT `fk_Complaint_User`
    FOREIGN KEY (`idUser`)
    REFERENCES `User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Complaint_Zone1`
    FOREIGN KEY (`idZone`)
    REFERENCES `Zone` (`idZone`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Complaint_Category1`
    FOREIGN KEY (`idCategory`)
    REFERENCES `Category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ClaimType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ClaimType` ;

CREATE TABLE IF NOT EXISTS `ClaimType` (
  `idClaimType` INT UNSIGNED NOT NULL,
  `name` VARCHAR(80) NOT NULL,
  `typeInCharge` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `idCategory` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idClaimType`),
  INDEX `fk_ClaimType_Category1_idx` (`idCategory` ASC),
  CONSTRAINT `fk_ClaimType_Category1`
    FOREIGN KEY (`idCategory`)
    REFERENCES `Category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FollowUp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FollowUp` ;

CREATE TABLE IF NOT EXISTS `FollowUp` (
  `idFollowUp` INT NOT NULL AUTO_INCREMENT,
  `idComplaint` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idFollowUp`),
  INDEX `fk_FollowUp_Complaint1_idx` (`idComplaint` ASC),
  CONSTRAINT `fk_FollowUp_Complaint1`
    FOREIGN KEY (`idComplaint`)
    REFERENCES `Complaint` (`idComplaint`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;




#insert category

INSERT INTO `hackathon76api`.`Category` (`name`, `type`) VALUES ('Eau', '1');
INSERT INTO `hackathon76api`.`Category` (`name`, `type`) VALUES ('Electricité', '1');
INSERT INTO `hackathon76api`.`Category` (`name`, `type`) VALUES ('Propreté', '1');
INSERT INTO `hackathon76api`.`Category` (`name`, `type`) VALUES ('Meunuiserie', '1');
INSERT INTO `hackathon76api`.`Category` (`name`, `type`) VALUES ('Toiture', '1');
INSERT INTO `hackathon76api`.`Category` (`name`, `type`) VALUES ('Sols/Murs', '1');
INSERT INTO `hackathon76api`.`Category` (`name`, `type`) VALUES ('Autres', '1');


INSERT INTO `hackathon76api`.`Category` (`name`, `type`) VALUES ('Ascenceur', '2');
INSERT INTO `hackathon76api`.`Category` (`name`, `type`) VALUES ('Chauffage', '2');
INSERT INTO `hackathon76api`.`Category` (`name`, `type`) VALUES ('Propreté', '2');
INSERT INTO `hackathon76api`.`Category` (`name`, `type`) VALUES ('Meunuiserie', '2');
INSERT INTO `hackathon76api`.`Category` (`name`, `type`) VALUES ('Toiture', '2');
INSERT INTO `hackathon76api`.`Category` (`name`, `type`) VALUES ('Sols/Murs', '2');
INSERT INTO `hackathon76api`.`Category` (`name`, `type`) VALUES ('Espaces verts', '2');
INSERT INTO `hackathon76api`.`Category` (`name`, `type`) VALUES ('Eau', '2');
INSERT INTO `hackathon76api`.`Category` (`name`, `type`) VALUES ('Electricité', '2');
INSERT INTO `hackathon76api`.`Category` (`name`, `type`) VALUES ('Autres', '2');


INSERT INTO `hackathon76api`.`ClaimType` (`name`, `typeInCharge`, `idCategory`) VALUES ('Problème de robinet', '3', '1');
INSERT INTO `hackathon76api`.`ClaimType` (`name`, `typeInCharge`, `idCategory`) VALUES ("Chasse d'eau", '3', '1');
INSERT INTO `hackathon76api`.`ClaimType` (`name`, `typeInCharge`, `idCategory`) VALUES ('Appareils sanitaires', '3', '1');
INSERT INTO `hackathon76api`.`ClaimType` (`name`, `typeInCharge`, `idCategory`) VALUES ('Chaudière', '3', '1');
INSERT INTO `hackathon76api`.`ClaimType` (`name`, `typeInCharge`, `idCategory`) VALUES ('Cumulus', '3', '1');


INSERT INTO `hackathon76api`.`ClaimType` (`name`, `typeInCharge`, `idCategory`) VALUES ("Colonne d'evacuation/Eau pluviale", '2', '1');

INSERT INTO `hackathon76api`.`ClaimType` (`name`, `typeInCharge`, `idCategory`) VALUES ('Débordements appareils', '1', '1');
INSERT INTO `hackathon76api`.`ClaimType` (`name`, `typeInCharge`, `idCategory`) VALUES ('Joint deféctueux', '1', '1');

INSERT INTO `hackathon76api`.`User` ( `email`, `password`, `name`, `phone`) VALUES ('hulck@wixiweb.fr', 'wixiweb', 'Hulck Hogan', '0982417945');



